TABLES = {
    "Members": 'CREATE TABLE Members (UserID BIGINT NOT NULL UNIQUE, Username TEXT NOT NULL, MsgsSent BIGINT NOT NULL, PRIMARY KEY(UserID));',
    "Reports": 'CREATE TABLE Reports (ID BIGINT NOT NULL UNIQUE, ReporterID BIGINT NOT NULL, UserID BIGINT NOT NULL, Reason TEXT NOT NULL, ReportDate TEXT, Resolved BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(ID))',
    "Roles": 'CREATE TABLE Roles (RoleID BIGINT NOT NULL UNIQUE, RoleName TEXT NOT NULL UNIQUE, RoleKey TEXT NOT NULL UNIQUE, PRIMARY KEY(RoleID))'
}
